namespace Salus.Exceptions;

/// <summary>
/// The exception that is thrown when an auto-generated key is used when this is not allowed.
/// </summary>
public class AutoGeneratedKeyException : SalusException
{
    public AutoGeneratedKeyException(string typeName, string propertyName)
        :base($"Type {typeName} has a key property {propertyName} which is auto-generated - that is not allowed because it prevents inserts from being idempotent")
    {
    }
}
