// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalusExampleChild;

#nullable disable

namespace SalusExampleChild.Migrations
{
    [DbContext(typeof(ChildContext))]
    partial class ChildContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Salus.Models.Entities.SalusSaveEntity<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedMessageSendAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFailedMessageSendAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextMessageSendAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaveJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedDateTimeUtc", "NextMessageSendAttemptUtc");

                    b.ToTable("SalusSaves");
                });

            modelBuilder.Entity("SalusExampleChild.ExampleData", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data1")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExampleData");
                });
#pragma warning restore 612, 618
        }
    }
}
