// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalusExampleParent;

#nullable disable

namespace SalusExampleParent.Migrations
{
    [DbContext(typeof(ExampleDbContext))]
    [Migration("20230311142232_AddExtraDataColumn")]
    partial class AddExtraDataColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Salus.Models.Entities.SalusSaveEntity<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedMessageSendAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFailedMessageSendAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextMessageSendAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SaveJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedDateTimeUtc", "NextMessageSendAttemptUtc");

                    b.ToTable("SalusSaves");
                });

            modelBuilder.Entity("SalusExampleParent.ExampleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data2")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExampleData");
                });
#pragma warning restore 612, 618
        }
    }
}
