// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalusExampleParent;

#nullable disable

namespace SalusExampleParent.Migrations
{
    [DbContext(typeof(ExampleDbContext))]
    [Migration("20230303171110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Salus.Models.SalusUpdateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedMessageSendAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFailedMessageSendAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextMessageSendAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompletedDateTimeUtc", "FailedMessageSendAttempts");

                    b.ToTable("SalusDataChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
